import './globals.css'
import "tw-elements/dist/css/tw-elements.min.css";

import { Poppins } from "next/font/google";

const poppins = Poppins({ weight: ["400","600"], subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
